# Created by: Ganbold Tsagaankhuu <ganbold@FreeBSD.org>
# $FreeBSD$

MASTERDIR=      ${.CURDIR}/../py-grpcio-tools
PLIST=          ${.CURDIR}/pkg-plist

USES=           localbase:ldflags python:3.3+

.include "${MASTERDIR}/Makefile"
